[workspace]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>"]
channels = ["conda-forge"]
name = "predictive-model-imbalanced-classification"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
scikit-learn = ">=1.6.1,<2"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.3,<4"
plotly = ">=6.0.1,<7"
nbformat = ">=5.10.4,<6"
imbalanced-learn = ">=0.13.0,<0.14"
skrub = ">=0.5.3,<0.6"
skore = ">=0.8.3,<0.9"
ipywidgets = ">=8.1.7,<9"
